/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.hotel.view;

/**
 *
 * @author pined
 */


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
import com.hotel.dao.HabitacionDAO;
import com.hotel.model.Habitacion;
import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.math.BigDecimal;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.ListSelectionModel;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;

public class HabitacionView extends JFrame {
    
    private JPanel panelBotones, panelBusqueda, panelTabla;
    private JButton btnNuevo, btnEditar, btnEliminar, btnRefrescar, btnCerrar;
    private JTextField txtBusqueda;
    private JButton btnBuscar;
    private JTable tablaHabitaciones;
    private DefaultTableModel modeloTabla;
    private JScrollPane scrollPane;
    
    private HabitacionDAO habitacionDAO;
    private List<Habitacion> listaHabitaciones;
    
    public HabitacionView() {
        habitacionDAO = new HabitacionDAO();
        initComponents();
        configurarVentana();
        configurarEventos();
        cargarDatos();
    }
    
    private void initComponents() {
        // Panel de botones
        panelBotones = new JPanel();
        panelBotones.setLayout(new FlowLayout(FlowLayout.LEFT));
        
        btnNuevo = new JButton("Nuevo");
        btnEditar = new JButton("Editar");
        btnEliminar = new JButton("Eliminar");
        btnRefrescar = new JButton("Refrescar");
        btnCerrar = new JButton("Cerrar");
        
        panelBotones.add(btnNuevo);
        panelBotones.add(btnEditar);
        panelBotones.add(btnEliminar);
        panelBotones.add(btnRefrescar);
        panelBotones.add(btnCerrar);
        
        // Panel de búsqueda
        panelBusqueda = new JPanel();
        panelBusqueda.setLayout(new FlowLayout(FlowLayout.LEFT));
        
        JLabel lblBuscar = new JLabel("Buscar por tipo:");
        txtBusqueda = new JTextField(20);
        btnBuscar = new JButton("Buscar");
        
        panelBusqueda.add(lblBuscar);
        panelBusqueda.add(txtBusqueda);
        panelBusqueda.add(btnBuscar);
        
        // Panel de tabla
        panelTabla = new JPanel();
        panelTabla.setLayout(new BorderLayout());
        
        modeloTabla = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
            
            @Override
            public Class<?> getColumnClass(int columnIndex) {
                if (columnIndex == 2) {
                    return BigDecimal.class;
                } else if (columnIndex == 4) {
                    return String.class;
                }
                return super.getColumnClass(columnIndex);
            }
        };
        
        modeloTabla.addColumn("ID");
        modeloTabla.addColumn("Tipo");
        modeloTabla.addColumn("Precio");
        modeloTabla.addColumn("Capacidad");
        modeloTabla.addColumn("Estado");
        
        tablaHabitaciones = new JTable(modeloTabla);
        tablaHabitaciones.getTableHeader().setReorderingAllowed(false);
        tablaHabitaciones.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tablaHabitaciones.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        
        scrollPane = new JScrollPane(tablaHabitaciones);
        panelTabla.add(scrollPane, BorderLayout.CENTER);
    }
    
    private void configurarVentana() {
        setTitle("Gestión de Habitaciones");
        setSize(800, 500);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        
        getContentPane().setLayout(new BorderLayout());
        getContentPane().add(panelBotones, BorderLayout.NORTH);
        getContentPane().add(panelTabla, BorderLayout.CENTER);
        getContentPane().add(panelBusqueda, BorderLayout.SOUTH);
    }
    
    private void configurarEventos() {
        btnNuevo.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                abrirDialogoNuevo();
            }
        });
        
        btnEditar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                editarHabitacion();
            }
        });
        
        btnEliminar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                eliminarHabitacion();
            }
        });
        
        btnRefrescar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                cargarDatos();
            }
        });
        
        btnCerrar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
            }
        });
        
        btnBuscar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                buscarHabitaciones();
            }
        });
        
        tablaHabitaciones.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2) {
                    editarHabitacion();
                }
            }
        });
    }
    
    private void cargarDatos() {
        // Limpiar tabla
        modeloTabla.setRowCount(0);
        
        // Obtener datos
        listaHabitaciones = habitacionDAO.getAll();
        
        // Llenar tabla
        for (Habitacion habitacion : listaHabitaciones) {
            Object[] fila = {
                habitacion.getIdHabitacion(),
                habitacion.getTipo(),
                habitacion.getPrecio(),
                habitacion.getCapacidad(),
                habitacion.getEstado()
            };
            modeloTabla.addRow(fila);
        }
        
        // Actualizar estado de botones
        actualizarEstadoBotones();
    }
    
    private void buscarHabitaciones() {
        String textoBusqueda = txtBusqueda.getText().trim();
        
        if (textoBusqueda.isEmpty()) {
            cargarDatos();
            return;
        }
        
        // Limpiar tabla
        modeloTabla.setRowCount(0);
        
        // Buscar habitaciones
        listaHabitaciones = habitacionDAO.searchByType(textoBusqueda);
        
        // Llenar tabla
        for (Habitacion habitacion : listaHabitaciones) {
            Object[] fila = {
                habitacion.getIdHabitacion(),
                habitacion.getTipo(),
                habitacion.getPrecio(),
                habitacion.getCapacidad(),
                habitacion.getEstado()
            };
            modeloTabla.addRow(fila);
        }
        
        // Actualizar estado de botones
        actualizarEstadoBotones();
    }
    
    private void abrirDialogoNuevo() {
        HabitacionDialog dialogo = new HabitacionDialog(this, true);
        dialogo.setVisible(true);
        
        if (dialogo.isAceptado()) {
            cargarDatos();
        }
    }
    
    private void editarHabitacion() {
        int filaSeleccionada = tablaHabitaciones.getSelectedRow();
        
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this,
                    "Debe seleccionar una habitación para editar",
                    "Editar habitación", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int idHabitacion = (int) tablaHabitaciones.getValueAt(filaSeleccionada, 0);
        
        Habitacion habitacionSeleccionada = habitacionDAO.getById(idHabitacion);
        
        if (habitacionSeleccionada != null) {
            HabitacionDialog dialogo = new HabitacionDialog(this, true, habitacionSeleccionada);
            dialogo.setVisible(true);
            
            if (dialogo.isAceptado()) {
                cargarDatos();
            }
        }
    }
    
    private void eliminarHabitacion() {
        int filaSeleccionada = tablaHabitaciones.getSelectedRow();
        
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this,
                    "Debe seleccionar una habitación para eliminar",
                    "Eliminar habitación", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int idHabitacion = (int) tablaHabitaciones.getValueAt(filaSeleccionada, 0);
        String tipoHabitacion = (String) tablaHabitaciones.getValueAt(filaSeleccionada, 1);
        
        int opcion = JOptionPane.showConfirmDialog(this,
                "¿Está seguro que desea eliminar la habitación " + tipoHabitacion + "?",
                "Confirmar eliminación", JOptionPane.YES_NO_OPTION);
        
        if (opcion == JOptionPane.YES_OPTION) {
            boolean resultado = habitacionDAO.delete(idHabitacion);
            
            if (resultado) {
                JOptionPane.showMessageDialog(this,
                        "Habitación eliminada correctamente",
                        "Eliminar habitación", JOptionPane.INFORMATION_MESSAGE);
                cargarDatos();
            } else {
                JOptionPane.showMessageDialog(this,
                        "Error al eliminar la habitación. Es posible que tenga reservas asociadas.",
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    
    private void actualizarEstadoBotones() {
        boolean hayFilas = tablaHabitaciones.getRowCount() > 0;
        btnEditar.setEnabled(hayFilas);
        btnEliminar.setEnabled(hayFilas);
    }
    
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | 
                IllegalAccessException | UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HabitacionView.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                new HabitacionView().setVisible(true);
            }
        });
    }
}
    
/*
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

 */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

